app.py
# stdlib
import datetime
import os 

# 3rd party 
from flask import Flask
from flask.ext.sqlalchemy import SQLAlchemy

# local
from database import db
from routes.play import routes as play_routes # noqa
from routes.index import routes as index_routes # noqa


def create_app():
	app = Flask(__name__)
	app.debug = True

	# Point application to psql database, initialize 
	app.config['SQLALCHEMY_DATABASE_URI'] = os.environ['DATABASE_URL']
	app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
	db.init_app(app) 
	
	# Register the route files
	app.register_blueprint(play_routes)
	app.register_blueprint(index_routes)
	
	# Set secret key for session, set a lifetime on the session
	app.secret_key = os.environ['APP_SECRET_KEY']
	app.permanent_session_lifetime = datetime.timedelta(hours=8)
	return app


if __name__ == "__main__":
	app = create_app()
	app.run()

routes/index.py
# stdlib
import uuid
import re

# 3rd party
from flask import \
    Blueprint,\
    current_app, \
    request,\
    redirect, \
    render_template, \
    session, \
    url_for

 # local
from database import Database

routes = Blueprint('index_routes', __name__, template_folder='templates')
db = Database()
MAX_USER_LENGTH = 50
PASSWORD_RE = '[A-Za-z0-9@#$%^&+=]{6,100}'


@routes.route("/")
def index():
	login_error = request.args.get('login_error')
	create_error = request.args.get('create_error')
	if login_error:
		return render_template('index.html', login_error=login_error)
	if create_error:
		return render_template('index.html', create_error=create_error)
	return render_template('index.html')

@routes.route("/create_account")
def create():
	username = request.args.get('username')
	password = request.args.get('password')

	# Filter username
	if not username:
		return redirect(url_for('index_routes.index', create_error="Please enter a valid username"))
	if len(username) > MAX_USER_LENGTH:
		return redirect(url_for('index_routes.index', create_error="Username cannot exceed 50 characters"))
	if not username.isalnum():
		return redirect(url_for('index_routes.index', create_error="Usernames can only contain a-z, A-Z, or 0-9"))
	# Check if username exists
	if db.account_exists(username):
		return redirect(url_for('index_routes.index', create_error="The username '{}' is already taken".format(username)))

	# Filter password
	if not re.match(PASSWORD_RE, password):
		return redirect(url_for('index_routes.index', create_error="Invalid password"))
	
	# Create user ID, add user to db, set cookie for gameplay, redirect to game
	user_id = uuid.uuid4().hex
	session['user_id'] = user_id 
	db.create_new_user(username, str(user_id), password)
	return redirect(url_for('play_routes.simon_says'))

@routes.route("/login")
def login():
	username = request.args.get('username')
	password = request.args.get('password')

	# Filter username
	if not username:
		return redirect(url_for('index_routes.index', login_error="Please enter a valid username"))
	if len(username) > MAX_USER_LENGTH:
		return redirect(url_for('index_routes.index', login_error="Username cannot exceed 50 characters"))
	if not username.isalnum():
		return redirect(url_for('index_routes.index', login_error="Usernames can only contain a-z, A-Z, or 0-9"))

	# Check if username exists
	if not db.account_exists(username):
		return redirect(url_for('index_routes.index', login_error="The username '{}' does not exist".format(username)))

	# Filter password
	if not re.match(PASSWORD_RE, password):
		return redirect(url_for('index_routes.index', login_error="Invalid password"))

	# Authenticate
	user_id = db.authenticate_user(username, password)
	if not user_id:
		return redirect(url_for('index_routes.index', login_error="Invalid credentials"))
	
	# Set cookie for gameplay, redirect to game
	session['user_id'] = user_id 
	return redirect(url_for('play_routes.simon_says'))

@routes.route("/logout")
def logout():
	session.clear()
	return redirect(url_for('index_routes.index'))
	

routes/play.py
# stdlib
import json
from random import randint

# 3rd party
from flask import \
    Blueprint,\
    current_app, \
    request,\
    redirect, \
    render_template, \
    session, \
    url_for

 # local
from database import Database

db = Database()

routes = Blueprint('play_routes', __name__, template_folder='templates')


# Reset the session timeout while the user is playing
@routes.before_request
def before_request():
    session.permanent = True
    session.modified = True

@routes.route("/play")
def simon_says():
	user_id = session.get('user_id')

	# Check if the user has a valid session
	if not user_id:
		return redirect(url_for('index_routes.login'))

	# Check if the cookie is valid
	user = db.get_username(user_id)
	if not user:
		return redirect(url_for('index_routes.login'))

	return render_template('simon_says.html', user=user, high_score=db.get_high_score(user_id), top_users=db.get_top_users())

@routes.route("/get-move", methods=['POST', 'GET'])
def get_move():
	user_id = session.get('user_id')
	
	# Check if the user has a valid session
	if not user_id:
		return redirect(url_for('index_routes.login'))

	data = json.loads(request.data)
	moves = data.get('moves')
	new_game = data.get('new')

	# Check if the user has started a new game
	if new_game:
		session['score'] = 0
		session['moves'] = []

	# Get the users score, get a new move
	users_score = session.get('score')
	moves.append(randint(1, 4))
	session['moves'] = moves

	return json.dumps({'moves': moves, 'user': users_score})

@routes.route("/check-move", methods=['POST'])
def check_move():
	user_id = session.get('user_id')

	# Check if the user has a valid session
	if not user_id:
		return redirect(url_for('index_routes.login'))

	data = json.loads(request.data)
	simons_moves = data.get('simons_moves')
	users_moves = data.get('moves')
	timeout = data.get('timeout')
	
	len_users_moves = len(users_moves)
	len_simons_moves = len(simons_moves)

	users_score = session.get('score')

	def lose():
		new_hs = db.update_high_score(user_id, users_score)
		if new_hs is None:
			return json.dumps({'valid': False, 'user': users_score})
		return json.dumps({'valid': False, 'user': users_score, 'high_score': new_hs})
		
	# Check if the user has made a move
	if len_users_moves == 0:
		return lose()

	# Check if the user has run out of time
	if timeout and len_users_moves < len_simons_moves:
		return lose()

	# A user should never have more moves than simon, but JIC
	if len_users_moves > len_simons_moves:
		return lose()

	# Cast simons moves to the length of user moves and compare
	simons_moves = simons_moves[:len_users_moves]
	if simons_moves == users_moves:
		if len_simons_moves == len_users_moves:
			users_score += 1
			session['score'] = users_score
		return json.dumps({'valid': True, 'user': users_score})
	return lose()

templates/index.html
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/simon.css') }}"/>
<link href="https://fonts.googleapis.com/css?family=Dancing+Script|Rubik" rel="stylesheet">
<title>Simon Says</title>

<div class="row">
	<h1>Simon Says</h1>
</div>

<div class="row auth-form">
	
	<form action="{{ url_for('index_routes.login') }}">
	  <h2>Existing User</h2><br><br>
	  <input type="text" name="username" placeholder="username" class="input"><br>
	  <input type="password" name="password" placeholder="password" class="input"><br>
	  <input type="submit" value="Login" class="button">
	  {% if login_error %}
  			<h3>{{login_error}}</h3>
  		{% endif %}
	</form>
</div>	

<div class="row auth-form">
	<form action="{{ url_for('index_routes.create') }}">
		<h2>New User</h2><br><br>
  		<input type="text" name="username" placeholder="username" class="input"><br>
  		<input type="password" name="password" placeholder="password" class="input"><br>
  		<input type="submit" value="Create Account" class="button"><br>
  		{% if create_error %}
  			<h3>{{create_error}}</h3>
  		{% endif %}
	</form>
</div>

templates/simon_says.html
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/simon.css') }}"/>
<link href="https://fonts.googleapis.com/css?family=Dancing+Script|Rubik" rel="stylesheet">
<title>Simon Says</title>
<div class=page>
  <div class="row">
    <a class="button logout-button" href="{{ url_for('index_routes.logout') }}">Logout</a>
    <h1>Simon Says</h1>
  </div>
  <div class="row">
    <div class="column">
      <div class="score">
        <h4>Username</h4><br>
        <h5> {{ user }} </h5><br><br>
        <h4>High Score</h4><br>
        <h5 id="highScore">{{ high_score }}</h5>
      </div>
    </div>
  	<div class='column'>
      <svg width="400" height="400">
        <rect id="top-left" width="195" height="195" rx="20" ry="20"/>
        <rect id="top-right" x="200" width="195" height="195" rx="20" ry="20"/>
        <rect id="bottom-left" y="200" width="195" height="195" rx="20" ry="20"/>
        <rect id="bottom-right" x="200" y="200" width="195" height="195" rx="20" ry="20"/>
        <g>
          <circle cx="200" cy="200" r="40" fill="white"/>
          <text id="yourScore" x="200" y="212"></text>
        </g>
      </svg>
    </div>
    <div class="column">
      <div class="stats">
        <h4>Top User Stats</h4>
        <table class="high-scores">
          <tr>
            <th>Score</th>
            <th>User</th> 
          </tr>
          {% for user in top_users %}
          <tr>
            <td>{{ user.high_score }}</td> 
            <td>{{ user.username }}</td>
          </tr>
          {% endfor %}
        </table>
      </div>
    </div>
  </div>
  <div class="row">
    <div id='container'>
    </div>
  </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://fb.me/react-15.1.0.js"></script>
<script src="https://fb.me/react-dom-15.1.0.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.18.1/babel.min.js"></script>
<script type="text/babel" src="{{ url_for('static', filename='js/simon.jsx') }}"></script>